### ISSUE TITLE
OpenAIParamModel Object Not Subscriptable - Unable to Run eval.py

### ISSUE THREAD

**Issue by zimingyou01** [InfiAgent/InfiAgent#26]
Hello developers,

I encountered an issue while running eval.py in the InfiAgent project. The process failed with the following error:
```
TypeError: 'OpenAIParamModel' object is not subscriptable
```
The detailed logs:

python .. /.. /pipeline/activities/eval.py --llm $MODEL --api_key $OPENAI_API_KEY --base_url $OPENAI_BASE_URL --config_path $CONFIG_PATH
input_text: Calculate the mean fare paid by the passengers.
concepts: ['Summary Statistics']
file_path: data/da-dev-tables/test_ave.csv
MyUploadedFile(name=test_ave.csv, size=55169, type=application/octet-stream)
> /data1/yzm/InfiAgent/pipeline/activities/eval.py(198)main()
-> response = await predict(
(Pdb) n
> /data1/yzm/InfiAgent/pipeline/activities/eval.py(199)main()
-> prompt=prompt,
(Pdb) 
> /data1/yzm/InfiAgent/pipeline/activities/eval.py(200)main()
-> model_name=model_name,
(Pdb) 
> /data1/yzm/InfiAgent/pipeline/activities/eval.py(201)main()
-> config_path=args.config_path,
(Pdb) 
> /data1/yzm/InfiAgent/pipeline/activities/eval.py(202)main()
-> uploaded_files=[uploaded_file]
(Pdb) n
> /data1/yzm/InfiAgent/pipeline/activities/eval.py(198)main()
-> response = await predict(
(Pdb) n
INFO:infiagent_logger:[] : Original CSV file delimiter is ',', no need to convert.
INFO:infiagent_logger:[] : Session Creation Latency: 0.05075216293334961
INFO:infiagent_logger:[] : Instruction message: Question: Calculate the mean fare paid by the passengers.
Calculate the mean fare using Python's built-in statistics module or appropriate statistical method in pandas. Rounding off the answer to two decimal places.

INFO:infiagent_logger:[] : Agent request: {'sandbox_id': 'TwfaF0NJlyqm', 'messages': [Message(role=<RoleType.System: 1>, content='User uploaded the following files: /home/yzm/miniconda3/envs/infiagent/lib/python3.9/site-packages/infiagent/tmp/upload_files/TwfaF0NJlyqm/test_ave.csv\n', raw_content=''), Message(role=<RoleType.User: 0>, content="Question: Calculate the mean fare paid by the passengers.\nCalculate the mean fare using Python's built-in statistics module or appropriate statistical method in pandas. Rounding off the answer to two decimal places.\n", raw_content='')], 'input_files': [MediaFile(file_name='test_ave.csv', file_content=None, tos_path=None, sandbox_path='/home/yzm/miniconda3/envs/infiagent/lib/python3.9/site-packages/infiagent/tmp/upload_files/TwfaF0NJlyqm/test_ave.csv')], 'sandbox_status': None, 'is_cn': False}
INFO:infiagent_logger:[] : Send prompt to LLM:
Answer the following questions as best you can. You have access to the following tools:
python_code_sandbox[input]: this tool can help to run python script with python code as input
.
Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do

Action: the action to take, should be one of [python_code_sandbox]

Action Input:
```python
[the input to the action]
```
Observation: the result of the action

... (this Thought/Action/Action Input/Observation can repeat N times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question
If you have any files outputted write them to "./"
Do not use things like plot.show() as it will not work instead write them out "./"
Begin!

Question: User uploaded the following files: /home/yzm/miniconda3/envs/infiagent/lib/python3.9/site-packages/infiagent/tmp/upload_files/TwfaF0NJlyqm/test_ave.csv

Question: Calculate the mean fare paid by the passengers.
Calculate the mean fare using Python's built-in statistics module or appropriate statistical method in pandas. Rounding off the answer to two decimal places.

Thought:

Exception: 'OpenAIParamModel' object is not subscriptable
ERROR:infiagent_logger:[] : LLM iteration 1 out of 3 failed. Error: 1 validation error for BaseCompletion
content
  Input should be a valid string [type=string_type, input_value=TypeError("'OpenAIParamMo... t is not subscriptable"), input_type=TypeError]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
Traceback (most recent call last):
  File "/home/yzm/miniconda3/envs/infiagent/lib/python3.9/site-packages/infiagent/agent/react/async_react_agent.py", line 147, in _single_round_thought
    llm_response = await self._get_llm_response(instruction)
  File "/home/yzm/miniconda3/envs/infiagent/lib/python3.9/site-packages/infiagent/agent/react/async_react_agent.py", line 164, in _get_llm_response
    response = await self. llm.async_completion(prompt)
  File "/home/yzm/miniconda3/envs/infiagent/lib/python3.9/site-packages/infiagent/llm/client/openai.py", line 100, in async_completion
    return BaseCompletion(state="error", content=exception)
  File "/home/yzm/miniconda3/envs/infiagent/lib/python3.9/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core. ValidationError: 1 validation error for BaseCompletion
content
  Input should be a valid string [type=string_type, input_value=TypeError("'OpenAIParamMo... t is not subscriptable"), input_type=TypeError]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
INFO:infiagent_logger:[] : Send prompt to LLM:
Answer the following questions as best you can. You have access to the following tools:
python_code_sandbox[input]: this tool can help to run python script with python code as input
.
Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do

Action: the action to take, should be one of [python_code_sandbox]

Action Input:
```python
[the input to the action]
```
Observation: the result of the action

... (this Thought/Action/Action Input/Observation can repeat N times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question
If you have any files outputted write them to "./"
Do not use things like plot.show() as it will not work instead write them out "./"
Begin!

Question: User uploaded the following files: /home/yzm/miniconda3/envs/infiagent/lib/python3.9/site-packages/infiagent/tmp/upload_files/TwfaF0NJlyqm/test_ave.csv

Question: Calculate the mean fare paid by the passengers.
Calculate the mean fare using Python's built-in statistics module or appropriate statistical method in pandas. Rounding off the answer to two decimal places.

Thought:

Exception: 'OpenAIParamModel' object is not subscriptable
ERROR:infiagent_logger:[] : LLM iteration 2 out of 3 failed. Error: 1 validation error for BaseCompletion
content
  Input should be a valid string [type=string_type, input_value=TypeError("'OpenAIParamMo... t is not subscriptable"), input_type=TypeError]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
Traceback (most recent call last):
  File "/home/yzm/miniconda3/envs/infiagent/lib/python3.9/site-packages/infiagent/agent/react/async_react_agent.py", line 147, in _single_round_thought
    llm_response = await self._get_llm_response(instruction)
  File "/home/yzm/miniconda3/envs/infiagent/lib/python3.9/site-packages/infiagent/agent/react/async_react_agent.py", line 164, in _get_llm_response
    response = await self. llm.async_completion(prompt)
  File "/home/yzm/miniconda3/envs/infiagent/lib/python3.9/site-packages/infiagent/llm/client/openai.py", line 100, in async_completion
    return BaseCompletion(state="error", content=exception)
  File "/home/yzm/miniconda3/envs/infiagent/lib/python3.9/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core. ValidationError: 1 validation error for BaseCompletion
content
  Input should be a valid string [type=string_type, input_value=TypeError("'OpenAIParamMo... t is not subscriptable"), input_type=TypeError]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
INFO:infiagent_logger:[] : Send prompt to LLM:
Answer the following questions as best you can. You have access to the following tools:
python_code_sandbox[input]: this tool can help to run python script with python code as input
.
Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do

Action: the action to take, should be one of [python_code_sandbox]

Action Input:
```python
[the input to the action]
```
Observation: the result of the action

... (this Thought/Action/Action Input/Observation can repeat N times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question
If you have any files outputted write them to "./"
Do not use things like plot.show() as it will not work instead write them out "./"
Begin!

Question: User uploaded the following files: /home/yzm/miniconda3/envs/infiagent/lib/python3.9/site-packages/infiagent/tmp/upload_files/TwfaF0NJlyqm/test_ave.csv

Question: Calculate the mean fare paid by the passengers.
Calculate the mean fare using Python's built-in statistics module or appropriate statistical method in pandas. Rounding off the answer to two decimal places.

Thought:

Exception: 'OpenAIParamModel' object is not subscriptable
ERROR:infiagent_logger:[] : LLM iteration 3 out of 3 failed. Error: 1 validation error for BaseCompletion
content
  Input should be a valid string [type=string_type, input_value=TypeError("'OpenAIParamMo... t is not subscriptable"), input_type=TypeError]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
Traceback (most recent call last):
  File "/home/yzm/miniconda3/envs/infiagent/lib/python3.9/site-packages/infiagent/agent/react/async_react_agent.py", line 147, in _single_round_thought
    llm_response = await self._get_llm_response(instruction)
  File "/home/yzm/miniconda3/envs/infiagent/lib/python3.9/site-packages/infiagent/agent/react/async_react_agent.py", line 164, in _get_llm_response
    response = await self. llm.async_completion(prompt)
  File "/home/yzm/miniconda3/envs/infiagent/lib/python3.9/site-packages/infiagent/llm/client/openai.py", line 100, in async_completion
    return BaseCompletion(state="error", content=exception)
  File "/home/yzm/miniconda3/envs/infiagent/lib/python3.9/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core. ValidationError: 1 validation error for BaseCompletion
content
  Input should be a valid string [type=string_type, input_value=TypeError("'OpenAIParamMo... t is not subscriptable"), input_type=TypeError]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
INFO:infiagent_logger:[] : Send prompt to LLM:
Answer the following questions as best you can. You have access to the following tools:
python_code_sandbox[input]: this tool can help to run python script with python code as input
.
Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do

Action: the action to take, should be one of [python_code_sandbox]

Action Input:
```python
[the input to the action]
```
Observation: the result of the action

... (this Thought/Action/Action Input/Observation can repeat N times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question
If you have any files outputted write them to "./"
Do not use things like plot.show() as it will not work instead write them out "./"
Begin!

Question: User uploaded the following files: /home/yzm/miniconda3/envs/infiagent/lib/python3.9/site-packages/infiagent/tmp/upload_files/TwfaF0NJlyqm/test_ave.csv

Question: Calculate the mean fare paid by the passengers.
Calculate the mean fare using Python's built-in statistics module or appropriate statistical method in pandas. Rounding off the answer to two decimal places.

Thought:

Exception: 'OpenAIParamModel' object is not subscriptable
ERROR:infiagent_logger:[] : LLM iteration 4 out of 3 failed. Error: 1 validation error for BaseCompletion
content
  Input should be a valid string [type=string_type, input_value=TypeError("'OpenAIParamMo... t is not subscriptable"), input_type=TypeError]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
Traceback (most recent call last):
  File "/home/yzm/miniconda3/envs/infiagent/lib/python3.9/site-packages/infiagent/agent/react/async_react_agent.py", line 147, in _single_round_thought
    llm_response = await self._get_llm_response(instruction)
  File "/home/yzm/miniconda3/envs/infiagent/lib/python3.9/site-packages/infiagent/agent/react/async_react_agent.py", line 164, in _get_llm_response
    response = await self. llm.async_completion(prompt)
  File "/home/yzm/miniconda3/envs/infiagent/lib/python3.9/site-packages/infiagent/llm/client/openai.py", line 100, in async_completion
    return BaseCompletion(state="error", content=exception)
  File "/home/yzm/miniconda3/envs/infiagent/lib/python3.9/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core. ValidationError: 1 validation error for BaseCompletion
content
  Input should be a valid string [type=string_type, input_value=TypeError("'OpenAIParamMo... t is not subscriptable"), input_type=TypeError]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
ERROR:infiagent_logger:[] : LLM iteration 4 exceed max retry 3. Aborting

Possible Cause:

I have modified the script (mainly focusing on the relative paths) and the error occurs in the `predict` function. It seems like there are some bugs in the package of `infiagent` and the async_completion method in openai.py is returning an exception that isn’t being properly converted to a string before being passed to BaseCompletion. This might be causing the validation error in Pydantic’s data model.

Questions:
	1.	How should I properly configure and run eval.py to avoid this error?
	2.     I am not sure is there any other bugs in the package. Could you please help me fix the bugs in the package infiagent to ensure running eval.py successfully to evaluate a new model by the benchmark?
Thank you for your assistance!

**Comment by zimingyou01** [comment]
I have fixed the bugs already. Thanks.

**Comment by sqy901** [comment]
How did you solve this problem?
