### ISSUE TITLE
Release of DAInstruct Dataset

### ISSUE THREAD

**Issue by Mayer123** [InfiAgent/InfiAgent#7]
Great work on constructing this new benchmark! I'm wondering if you have any plans for releasing the DAInstruct dataset?

**Comment by XianglongTan** [comment]
+1

**Comment by huxueyu** [comment]
> Great work on constructing this new benchmark! I'm wondering if you have any plans for releasing the DAInstruct dataset?

Apologies for the delayed response. We currently do not have plans to open-source the training dataset DAInstruct. However, we have already open-sourced DAAgent, and you are welcome to try it out~ If you have any other questions, please feel free to contact us.
